[project]
name = "array-api-stubs"
version = "0.0.1"
description = "foo"
authors = []
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.8"
keywords = []
classifiers = []
dependencies = []